// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate / Studio / generate use this URL. Must be an UNPOOLED connection:
    // Neon's pgBouncer transaction-mode pool doesn't support session-scoped
    // advisory locks, so `prisma migrate deploy` against the pooler times out
    // with P1002. `DIRECT_URL` isn't set in our Vercel envs, but Neon's
    // integration provides the unpooled connection as DATABASE_URL_UNPOOLED /
    // POSTGRES_URL_NON_POOLING — prefer those before falling back to the pooled
    // DATABASE_URL. The runtime PrismaClient still reads DATABASE_URL (pooled)
    // from env, so app queries continue to flow through the pool.
    url:
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"],
  },
});
