// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate / Studio / generate use this URL. Prefer DIRECT_URL when set
    // because Neon's pgBouncer transaction-mode pool doesn't support
    // session-scoped advisory locks — `prisma migrate deploy` against the
    // pooler times out with P1002. The runtime PrismaClient still reads
    // DATABASE_URL (the pooled connection) directly from env, so queries
    // continue to flow through the pool. Falls back to DATABASE_URL locally
    // where there's no separate pooler.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
