// TEMPORARY PREVIEW — not part of the PR. Renders the real ClientReport
// component with hand-built sample data so the layout can be viewed locally
// without a DB. Numbers mirror one WEEK of the Poncho campaign so the preview
// reflects the weekly-report framing (not real synced data). Delete before merge.
import type { ReportData } from "@/lib/reports/report-data";
import { ClientReport } from "@/components/reports/client-report";

// ClientReport reads useSearchParams (date-range control), which can't be
// statically prerendered without a Suspense boundary — render at request time.
export const dynamic = "force-dynamic";

const day = (n: number) =>
  new Date(2026, 5, 16 + n).toISOString().slice(0, 10); // Jun 16 → Jun 22

const MOCK: ReportData = {
  scope: { type: "client", teamId: "preview" },
  title: "Poncho",
  subtitle: "Weekly report",
  startDate: new Date(2026, 5, 16).toISOString(),
  endDate: new Date(2026, 5, 22).toISOString(),
  generatedAt: new Date().toISOString(),
  hero: {
    postsShipped: 33,
    totalViews: 6_120,
    totalEngagements: 142,
    engagementRate: 0.023,
    viralPosts: 9,
    viralThreshold: 240,
  },
  engagementBreakdown: { likes: 98, comments: 22, shares: 15, saves: 7 },
  platforms: [
    {
      platform: "INSTAGRAM",
      posts: 21,
      views: 4_350,
      engagements: 104,
      engagementRate: 0.024,
      viewsPerPost: 207,
    },
    {
      platform: "TIKTOK",
      posts: 12,
      views: 1_770,
      engagements: 38,
      engagementRate: 0.021,
      viewsPerPost: 148,
    },
  ],
  leaderPlatform: "INSTAGRAM",
  underperformingPlatform: "TIKTOK",
  trend: Array.from({ length: 7 }, (_, i) => ({
    date: day(i),
    views: Math.round(6_120 * Math.min(1, (i + 1) / 7) ** 1.3),
    engagements: Math.round(142 * Math.min(1, (i + 1) / 7) ** 1.3),
  })),
  topViralPosts: [
    {
      id: "p1",
      platform: "INSTAGRAM",
      caption: "she's a friend who actually replies.",
      link: "https://www.instagram.com/reel/1/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 20, 20).toISOString(),
      views: 1_240,
      engagements: 41,
      engagementRate: 0.033,
      creatorName: "Sample Creator A",
      creatorHandle: "creator_a",
    },
    {
      id: "p2",
      platform: "INSTAGRAM",
      caption: "poncho is literally catfishing me (in a good way).",
      link: "https://www.instagram.com/reel/2/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 19, 21).toISOString(),
      views: 980,
      engagements: 31,
      engagementRate: 0.0316,
      creatorName: "Sample Creator B",
      creatorHandle: "creator_b",
    },
    {
      id: "p3",
      platform: "TIKTOK",
      caption: "my therapist costs $200. this is free.",
      link: "https://www.tiktok.com/@creator_c/video/3",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 17, 19).toISOString(),
      views: 760,
      engagements: 22,
      engagementRate: 0.0289,
      creatorName: "Sample Creator C",
      creatorHandle: "creator_c",
    },
    {
      id: "p4",
      platform: "INSTAGRAM",
      caption: "more reliable than my real friends, honestly.",
      link: "https://www.instagram.com/reel/4/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 16, 22).toISOString(),
      views: 610,
      engagements: 19,
      engagementRate: 0.0311,
      creatorName: "Sample Creator A",
      creatorHandle: "creator_a",
    },
    {
      id: "p5",
      platform: "TIKTOK",
      caption: "planned my whole trip in 60 seconds.",
      link: "https://www.tiktok.com/@creator_d/video/5",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 18, 18).toISOString(),
      views: 540,
      engagements: 14,
      engagementRate: 0.0259,
      creatorName: "Sample Creator D",
      creatorHandle: "creator_d",
    },
    {
      id: "p6",
      platform: "INSTAGRAM",
      caption: "I sent voice notes at 2am. no human friend is doing this.",
      link: "https://www.instagram.com/reel/6/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 21, 23).toISOString(),
      views: 470,
      engagements: 13,
      engagementRate: 0.0277,
      creatorName: "Sample Creator B",
      creatorHandle: "creator_b",
    },
  ],
  topCaptions: [
    {
      id: "p1",
      platform: "INSTAGRAM",
      caption: "she's a friend who actually replies.",
      link: "https://www.instagram.com/reel/1/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 20, 20).toISOString(),
      views: 1_240,
      engagements: 41,
      engagementRate: 0.033,
      creatorName: "Sample Creator A",
      creatorHandle: "creator_a",
    },
    {
      id: "p2",
      platform: "INSTAGRAM",
      caption: "poncho is literally catfishing me (in a good way).",
      link: "https://www.instagram.com/reel/2/",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 19, 21).toISOString(),
      views: 980,
      engagements: 31,
      engagementRate: 0.0316,
      creatorName: "Sample Creator B",
      creatorHandle: "creator_b",
    },
    {
      id: "p3",
      platform: "TIKTOK",
      caption: "my therapist costs $200. this is free.",
      link: "https://www.tiktok.com/@creator_c/video/3",
      thumbnailUrl: null,
      postedAt: new Date(2026, 5, 17, 19).toISOString(),
      views: 760,
      engagements: 22,
      engagementRate: 0.0289,
      creatorName: "Sample Creator C",
      creatorHandle: "creator_c",
    },
  ],
  creators: [
    {
      creatorId: "c1",
      name: "Sample Creator A",
      handle: "creator_a",
      posts: 10,
      views: 2_050,
      engagements: 47,
      engagementRate: 0.023,
      bestPostViews: 1_240,
      bestPostCaption: "she's a friend who actually replies.",
    },
    {
      creatorId: "c2",
      name: "Sample Creator B",
      handle: "creator_b",
      posts: 9,
      views: 1_620,
      engagements: 39,
      engagementRate: 0.024,
      bestPostViews: 980,
      bestPostCaption: "poncho is literally catfishing me…",
    },
    {
      creatorId: "c3",
      name: "Sample Creator C",
      handle: "creator_c",
      posts: 8,
      views: 1_430,
      engagements: 30,
      engagementRate: 0.021,
      bestPostViews: 760,
      bestPostCaption: "my therapist costs $200. this is free.",
    },
    {
      creatorId: "c4",
      name: "Sample Creator D",
      handle: "creator_d",
      posts: 6,
      views: 1_020,
      engagements: 26,
      engagementRate: 0.025,
      bestPostViews: 540,
      bestPostCaption: "planned my whole trip in 60 seconds.",
    },
  ],
  captionLength: [
    { bucket: "0–50", posts: 7, avgViews: 112, avgEngagementRate: 0.02 },
    { bucket: "51–100", posts: 12, avgViews: 226, avgEngagementRate: 0.031 },
    { bucket: "101–150", posts: 9, avgViews: 154, avgEngagementRate: 0.018 },
    { bucket: "151+", posts: 5, avgViews: 71, avgEngagementRate: 0.008 },
  ],
  postingByDay: [
    { day: "Sun", posts: 3, avgViews: 96 },
    { day: "Mon", posts: 5, avgViews: 138 },
    { day: "Tue", posts: 6, avgViews: 214 },
    { day: "Wed", posts: 4, avgViews: 152 },
    { day: "Thu", posts: 6, avgViews: 228 },
    { day: "Fri", posts: 5, avgViews: 161 },
    { day: "Sat", posts: 4, avgViews: 104 },
  ],
  postingByHour: Array.from({ length: 24 }, (_, hour) => {
    const peak = [19, 20, 21, 22];
    const posts = peak.includes(hour) ? 4 : hour > 7 && hour < 23 ? 1 : 0;
    return {
      hour,
      posts,
      avgViews: posts ? 70 + ((hour * 6131) % 160) : 0,
    };
  }),
  wow: {
    posts: { thisWeek: 33, lastWeek: 31, delta: 2, pctChange: 0.0645 },
    views: { thisWeek: 6_120, lastWeek: 4_010, delta: 2_110, pctChange: 0.5262 },
    engagements: { thisWeek: 142, lastWeek: 96, delta: 46, pctChange: 0.4792 },
    viralPosts: { thisWeek: 9, lastWeek: 6, delta: 3, pctChange: 0.5 },
  },
};

export default function ReportPreviewPage() {
  return <ClientReport data={MOCK} />;
}
